export type SemanticKeywordGroup = {
  category: string;
  keywords: string[];
};

export const SEMANTIC_KEYWORD_GROUPS: SemanticKeywordGroup[] = [
  {
    category: "Autonomous AI Security Core",
    keywords: [
      "Autonomous AI Security",
      "AI-driven cybersecurity orchestrator",
      "AI security workforce",
      "agentic cybersecurity platform",
      "autonomous cyber defense",
      "AI security operations",
      "intelligent security automation",
      "continuous AI threat analysis",
      "security AI copilot",
      "adaptive cyber risk orchestration",
    ],
  },
  {
    category: "AI Code Audit and SAST",
    keywords: [
      "AI Code Audit",
      "AI security audit",
      "automated code audit",
      "secure code analysis",
      "SAST automation",
      "static application security testing",
      "logic flaw detection",
      "business logic vulnerability scan",
      "code vulnerability scanner",
      "risk-based code remediation",
    ],
  },
  {
    category: "Pentesting and Red Teaming",
    keywords: [
      "Pentesting AI Squad",
      "Autonomous Pen-testing",
      "AI-powered pentesting",
      "Autonomous Red-Teaming",
      "agent-based red team simulation",
      "offensive security simulation",
      "web penetration testing AI",
      "API penetration testing AI",
      "targeted infiltration simulation",
      "ethical hacking automation",
    ],
  },
  {
    category: "Live Attack Simulation",
    keywords: [
      "Live Attack Simulation",
      "Real-time Web Attack Simulation",
      "payload execution telemetry",
      "attack queue orchestration",
      "security stress simulation",
      "high-speed exploit simulation",
      "attack pipeline monitoring",
      "payload counter analytics",
      "live security operation console",
      "real-time exploitation workflow",
    ],
  },
  {
    category: "Web, API, and SaaS Security",
    keywords: [
      "SaaS security agents",
      "SaaS security scanner",
      "web application pentest",
      "API security testing",
      "API abuse detection",
      "auth flow security review",
      "session security analysis",
      "input validation audit",
      "multi-tenant SaaS security",
      "endpoint attack simulation",
    ],
  },
  {
    category: "Zero-day and Threat Detection",
    keywords: [
      "Zero-day AI detection",
      "zero-day exposure analysis",
      "real-time threat filtering",
      "runtime risk detection",
      "predictive security AI",
      "exploit chain analysis",
      "threat modeling AI",
      "continuous threat monitoring",
      "high-confidence vulnerability detection",
      "intelligent anomaly detection",
    ],
  },
  {
    category: "Cloud and Infrastructure Security",
    keywords: [
      "cloud security posture",
      "infrastructure attack simulation",
      "container security audit",
      "Kubernetes security validation",
      "network attack surface mapping",
      "identity and access security audit",
      "supply chain security scan",
      "dependency vulnerability detection",
      "configuration drift risk detection",
      "platform hardening intelligence",
    ],
  },
  {
    category: "DevSecOps and SDLC",
    keywords: [
      "DevSecOps automation",
      "secure SDLC",
      "secure release validation",
      "pre-deployment security checks",
      "CI/CD security gating",
      "code-to-runtime risk tracing",
      "security pipeline orchestration",
      "automated remediation guidance",
      "developer-first security tooling",
      "engineering security acceleration",
    ],
  },
  {
    category: "Compliance and Governance",
    keywords: [
      "enterprise security automation",
      "governance-driven security testing",
      "audit-ready security evidence",
      "compliance vulnerability reporting",
      "risk prioritization engine",
      "security control verification",
      "policy-aware security scanning",
      "SOC 2 security readiness",
      "ISO 27001 security validation",
      "regulatory cyber risk posture",
    ],
  },
  {
    category: "Agentic AI and LLM Security",
    keywords: [
      "LLM security auditing",
      "prompt injection defense",
      "hallucination-resistant security AI",
      "self-correcting AI audit",
      "agentic code reasoning",
      "AI model abuse detection",
      "model-integrated security controls",
      "AI workflow threat validation",
      "autonomous reasoning security engine",
      "multi-agent security orchestration",
    ],
  },
  {
    category: "Security Operations and SOC",
    keywords: [
      "SOC workflow automation",
      "security incident triage AI",
      "threat response acceleration",
      "event-driven security analytics",
      "real-time risk scoring",
      "high-priority finding routing",
      "cross-system vulnerability correlation",
      "security telemetry intelligence",
      "live investigation handoff",
      "security operations decision engine",
    ],
  },
  {
    category: "Agency and Developer Growth",
    keywords: [
      "agency security automation",
      "developer security productivity",
      "security-as-a-workflow platform",
      "client-facing pentest intelligence",
      "high-scale audit orchestration",
      "multi-project vulnerability management",
      "security delivery acceleration",
      "continuous validation for agencies",
      "autonomous security for startups",
      "enterprise-grade AI security platform",
    ],
  },
];

export const SEMANTIC_KEYWORDS = SEMANTIC_KEYWORD_GROUPS.flatMap((group) => group.keywords);
